#!/usr/bin/env python3
"""
Creates OmniBlend_Module_Documentation.xlsx using only Python stdlib (zipfile).
An xlsx file is a zip archive containing XML files.
"""

import zipfile
import os

OUTPUT_PATH = "/home/user/LubeOilSim/OmniBlend_Module_Documentation.xlsx"

# ---------------------------------------------------------------------------
# Helper: escape XML special chars
# ---------------------------------------------------------------------------
def xe(s):
    return (str(s)
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
            .replace("'", "&apos;"))

# ---------------------------------------------------------------------------
# Data
# ---------------------------------------------------------------------------
DISCLAIMER = ("Note: All timelines are tentative estimates. Actual durations will depend on "
              "site readiness, data availability, system access, and integration complexity.")

MODULES = [
    {
        "num": 1,
        "name": "Command Dashboard",
        "status": "Simulated / Built",
        "function": (
            "Central operations overview showing live KPIs (production volume, cost per batch, "
            "energy usage, equipment utilisation, on-spec rate), a live event feed of alerts, "
            "an operations timeline, an energy consumption heatmap, and equipment health meters."
        ),
        "current_state": (
            "Fully simulated — all values are generated by the simulation engine."
        ),
        "reqs": [
            "Production volumes from the manufacturing / ERP system",
            "Energy readings from building smart meters",
            "Equipment status signals from plant control systems (SCADA)",
            "Quality pass/fail results from the laboratory system (LIMS)",
            "Real alerts forwarded from SCADA, LIMS, and manufacturing systems",
        ],
        "phases": "Phase 3 (SCADA), Phase 4 (LIMS), Phase 5 (MES/ERP), Phase 8 (Energy)",
    },
    {
        "num": 2,
        "name": "Blend Simulator",
        "status": "Simulated / Built",
        "function": (
            "Manages blending batches through their full lifecycle — queued → mixing → "
            "sampling → lab → completed. Shows real-time batch temperature, mixing speed (RPM), "
            "progress percentage, and volume. Animated pipeline shows material flow between tanks."
        ),
        "current_state": (
            "Fully simulated — batch stages progress on a timer; temperature and RPM drift "
            "based on simulation engine ticks."
        ),
        "reqs": [
            "Batch stage signals from plant control systems (SCADA/PLC)",
            "Real-time blender temperature from thermocouple sensors",
            "Mixing speed feedback from Variable Frequency Drives",
            "Volume readings from flow meters or weighing systems",
            "Production orders imported from the manufacturing system (MES/ERP)",
        ],
        "phases": "Phase 3 (SCADA sensors), Phase 5 (MES/ERP orders)",
    },
    {
        "num": 3,
        "name": "Tank Digital Twin",
        "status": "Simulated / Built",
        "function": (
            "Visual tank farm layout showing all 12 tanks with animated fill levels, material "
            "types, temperatures, and status (Normal / Low / Critical). Supports drag-and-drop "
            "tank allocation and low-stock alerts with glowing indicators."
        ),
        "current_state": (
            "Fully simulated — fill levels drift with Gaussian noise; temperatures drift slowly "
            "per simulation tick."
        ),
        "reqs": [
            "Level sensors on each of the 12 tanks (ultrasonic or radar transmitters via SCADA)",
            "Temperature sensors per tank (thermocouple or RTD via SCADA)",
            "Tank material assignments from the manufacturing/ERP system",
            "Physical tank capacity data from plant datasheets (one-time configuration)",
        ],
        "phases": "Phase 3 (SCADA sensors), Phase 5 (material assignments from ERP)",
    },
    {
        "num": 4,
        "name": "Recipe Lab",
        "status": "Simulated / Built",
        "function": (
            "Create and modify lubricant formulations using ingredient sliders (base oil, "
            "viscosity modifier, antioxidant, detergent, PPD). AI engine predicts viscosity, "
            "flash point, and TBN in real time. Includes cost-per-litre display, three AI "
            "suggest modes (cost / quality / balanced), and a recipe library with 10 pre-loaded "
            "seed formulations."
        ),
        "current_state": (
            "Fully simulated — predictions use polynomial regression on synthetic data; costs "
            "are hardcoded; recipes are hardcoded seeds (SAE grades, hydraulic, gear oil, etc.) "
            "not the real plant product codes."
        ),
        "reqs": [
            "Real recipe formulations synced from the ERP system (SAP PP-PI master recipe) "
            "to replace hardcoded seeds",
            "Historical batch data (200+ batches) for training accurate ML prediction models",
            "Live supplier pricing feed for accurate cost-per-litre calculations",
        ],
        "phases": "Phase 5 (ERP recipe sync), Phase 6 (live pricing), Phase 7 (real ML models)",
    },
    {
        "num": 5,
        "name": "Quality AI Engine",
        "status": "Simulated / Built",
        "function": (
            "Live quality prediction graphs with confidence intervals, an off-spec risk meter "
            "(0–100%), AI recommendations with impact levels, and a side-by-side predicted vs "
            "actual quality comparison table."
        ),
        "current_state": (
            "Fully simulated — predictions are formula-based; confidence intervals are hardcoded "
            "at ±5%; the predicted vs actual comparison table shows dummy data; risk meter uses "
            "hardcoded thresholds."
        ),
        "reqs": [
            "Laboratory system (LIMS) integration to receive actual test results (viscosity, "
            "flash point, TBN) within 5 minutes of analyst sign-off",
            "Historical lab results (200–500 batches) to train accurate ML prediction models",
            "Real batch data to calculate genuine confidence intervals",
            "Automated off-spec alert triggering a batch hold when LIMS returns a fail",
        ],
        "phases": "Phase 4 (LIMS integration), Phase 7 (real ML models)",
    },
    {
        "num": 6,
        "name": "Supply & Cost Optimizer",
        "status": "Simulated / Built",
        "function": (
            "Multi-supplier selection interface showing price per litre, lead time, quality "
            "grade, and reliability score per supplier. AI optimizer suggests the cheapest and "
            "best-quality supplier mix. Dynamic cost breakdown pie chart and 6-month price trend "
            "charts."
        ),
        "current_state": (
            "Fully simulated — all supplier data (prices, lead times, quality grades, reliability "
            "scores) is hardcoded static data."
        ),
        "reqs": [
            "Live supplier pricing feeds via EDI or supplier REST APIs (updated daily)",
            "Lead times derived from ERP purchase order history",
            "Quality grades from incoming raw material QC results (LIMS)",
            "Reliability scores calculated from ERP on-time delivery history (rolling 12-month)",
        ],
        "phases": "Phase 5 (quality grades from LIMS), Phase 6 (live pricing and ERP data)",
    },
    {
        "num": 7,
        "name": "AI Control Panel",
        "status": "Simulated / Built",
        "function": (
            "Natural language command interface (e.g. \"Start blend B101\", \"Optimise recipe for "
            "cost\"). Includes quick command buttons, a what-if scenario comparison with radar "
            "charts (3 pre-configured scenarios), and injectable simulation events (equipment "
            "failure, material shortage, quality deviation)."
        ),
        "current_state": (
            "Functional simulator — commands are parsed using keyword/regex matching (no real "
            "NLP). Scenarios and event injection work within the simulator."
        ),
        "reqs": [
            "Claude API (Anthropic) integration to replace regex matching with real natural "
            "language understanding",
            "Connection routing from NL commands to all live module APIs",
            "Response caching and graceful fallback for API downtime",
        ],
        "phases": "Phase 8 (Claude API NLP integration)",
    },
]

PHASES = [
    {
        "phase": "Phase 1",
        "name": "Infrastructure Foundation",
        "weeks": "Weeks 1–4",
        "modules": "All (underpins everything)",
        "key_work": (
            "Cloud/server setup, database deployment, caching layer, SSL, "
            "environment separation, load testing"
        ),
    },
    {
        "phase": "Phase 2",
        "name": "Security & Access Control",
        "weeks": "Weeks 3–6 (overlaps Phase 1)",
        "modules": "All",
        "key_work": (
            "User authentication, role-based access (4 roles: Operator, Engineer, Manager, "
            "Read-Only), secure network tunnels between plant and platform, secrets management, "
            "audit logging"
        ),
    },
    {
        "phase": "Phase 3",
        "name": "SCADA / Plant Sensor Connection",
        "weeks": "Weeks 5–10",
        "modules": "Tank Digital Twin, Blend Simulator, Command Dashboard",
        "key_work": (
            "Connect 12 tank level + 12 tank temperature sensors; connect blender RPM and "
            "temperature; connect flow meters; forward SCADA alarms to event feed"
        ),
    },
    {
        "phase": "Phase 4",
        "name": "Laboratory System Integration",
        "weeks": "Weeks 8–14",
        "modules": "Quality AI Engine, Command Dashboard (On-Spec Rate KPI)",
        "key_work": (
            "Connect LIMS to receive real lab results within 5 minutes of sign-off; activate "
            "predicted vs actual panel; enable off-spec batch hold alerts; begin accumulating "
            "lab data for future ML training"
        ),
    },
    {
        "phase": "Phase 5",
        "name": "Manufacturing & ERP Sync",
        "weeks": "Weeks 12–18",
        "modules": "Blend Simulator, Recipe Lab, Tank Digital Twin, Command Dashboard",
        "key_work": (
            "Auto-import production orders; sync real recipe formulations from ERP (retire "
            "hardcoded seeds); bidirectional batch stage sync; material consumption data postback "
            "to ERP; real operations timeline"
        ),
    },
    {
        "phase": "Phase 6",
        "name": "Supplier Pricing Feed",
        "weeks": "Weeks 16–20",
        "modules": "Supply & Cost Optimizer, Recipe Lab",
        "key_work": (
            "Connect live supplier pricing; derive lead times from ERP purchase history; "
            "calculate reliability scores from on-time delivery data; Cost per Batch KPI "
            "becomes real"
        ),
    },
    {
        "phase": "Phase 7",
        "name": "ML Model Training",
        "weeks": "Weeks 18–24",
        "modules": "Recipe Lab, Quality AI Engine, Supply & Cost Optimizer",
        "key_work": (
            "Train viscosity, flash point, and TBN prediction models on 200+ real batches "
            "(target accuracy R²>0.92); train off-spec risk classifier; replace hardcoded "
            "confidence intervals with real model performance; upgrade AI recipe suggestions "
            "to use constrained optimisation"
        ),
    },
    {
        "phase": "Phase 8",
        "name": "Go-Live & Observability",
        "weeks": "Weeks 22–26",
        "modules": "AI Control Panel, Command Dashboard (Energy Heatmap)",
        "key_work": (
            "Activate Claude API for AI Control Panel NLP; connect energy heatmap to real "
            "building management data; set up application monitoring, log aggregation, and "
            "on-call alerting; operator training; phased go-live with 4-week support period"
        ),
    },
]

# ---------------------------------------------------------------------------
# Shared styles helper (inline styles embedded in XML)
# ---------------------------------------------------------------------------
# We use a simple shared-string table + styles approach.

def build_workbook():
    """
    Returns a dict of {filename: bytes} representing the xlsx archive.
    """
    files = {}

    # -----------------------------------------------------------------------
    # Collect all unique strings for the shared strings table
    # -----------------------------------------------------------------------
    all_strings = []
    string_index = {}

    def si(s):
        """Get or create shared-string index."""
        s = str(s)
        if s not in string_index:
            string_index[s] = len(all_strings)
            all_strings.append(s)
        return string_index[s]

    # -----------------------------------------------------------------------
    # Sheet 1: Module Overview
    # -----------------------------------------------------------------------
    sheet1_rows = []
    # Disclaimer row
    sheet1_rows.append([(si(DISCLAIMER), "s")])
    sheet1_rows.append([])  # blank
    # Header
    sheet1_rows.append([
        (si("Module #"), "s"),
        (si("Module Name"), "s"),
        (si("Status"), "s"),
        (si("Function / Description"), "s"),
        (si("Current State"), "s"),
        (si("Timeline Phases"), "s"),
    ])
    for m in MODULES:
        sheet1_rows.append([
            (si(m["num"]), "n"),
            (si(m["name"]), "s"),
            (si(m["status"]), "s"),
            (si(m["function"]), "s"),
            (si(m["current_state"]), "s"),
            (si(m["phases"]), "s"),
        ])

    # -----------------------------------------------------------------------
    # Sheet 2: Requirements to Go Live
    # -----------------------------------------------------------------------
    sheet2_rows = []
    sheet2_rows.append([(si(DISCLAIMER), "s")])
    sheet2_rows.append([])
    sheet2_rows.append([
        (si("Module #"), "s"),
        (si("Module Name"), "s"),
        (si("Requirement"), "s"),
    ])
    for m in MODULES:
        for req in m["reqs"]:
            sheet2_rows.append([
                (si(m["num"]), "n"),
                (si(m["name"]), "s"),
                (si(req), "s"),
            ])

    # -----------------------------------------------------------------------
    # Sheet 3: Tentative Timeline
    # -----------------------------------------------------------------------
    sheet3_rows = []
    sheet3_rows.append([(si(DISCLAIMER), "s")])
    sheet3_rows.append([])
    sheet3_rows.append([
        (si("Phase"), "s"),
        (si("Phase Name"), "s"),
        (si("Estimated Weeks"), "s"),
        (si("Modules Affected"), "s"),
        (si("Key Work"), "s"),
    ])
    for p in PHASES:
        sheet3_rows.append([
            (si(p["phase"]), "s"),
            (si(p["name"]), "s"),
            (si(p["weeks"]), "s"),
            (si(p["modules"]), "s"),
            (si(p["key_work"]), "s"),
        ])

    # -----------------------------------------------------------------------
    # Build shared strings XML
    # -----------------------------------------------------------------------
    ss_items = "".join(
        f"<si><t xml:space=\"preserve\">{xe(s)}</t></si>" for s in all_strings
    )
    shared_strings_xml = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        f'<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
        f'count="{len(all_strings)}" uniqueCount="{len(all_strings)}">'
        f'{ss_items}'
        f'</sst>'
    )
    files["xl/sharedStrings.xml"] = shared_strings_xml.encode("utf-8")

    # -----------------------------------------------------------------------
    # Build styles XML (minimal)
    # -----------------------------------------------------------------------
    # Font 0 = normal, Font 1 = bold
    # Fill 0 = none, Fill 1 = gray125 (required), Fill 2 = header blue
    # Border 0 = none
    # CellXf 0 = normal, 1 = bold, 2 = bold+blue fill, 3 = wrap
    styles_xml = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
        '<fonts count="3">'
        '<font><sz val="10"/><name val="Calibri"/></font>'
        '<font><b/><sz val="10"/><name val="Calibri"/></font>'
        '<font><b/><sz val="10"/><name val="Calibri"/><color rgb="FFFFFFFF"/></font>'
        '</fonts>'
        '<fills count="4">'
        '<fill><patternFill patternType="none"/></fill>'
        '<fill><patternFill patternType="gray125"/></fill>'
        '<fill><patternFill patternType="solid"><fgColor rgb="FF2F5496"/></patternFill></fill>'
        '<fill><patternFill patternType="solid"><fgColor rgb="FFFFE699"/></patternFill></fill>'
        '</fills>'
        '<borders count="2">'
        '<border><left/><right/><top/><bottom/><diagonal/></border>'
        '<border>'
        '<left style="thin"><color rgb="FF9E9E9E"/></left>'
        '<right style="thin"><color rgb="FF9E9E9E"/></right>'
        '<top style="thin"><color rgb="FF9E9E9E"/></top>'
        '<bottom style="thin"><color rgb="FF9E9E9E"/></bottom>'
        '<diagonal/>'
        '</border>'
        '</borders>'
        '<cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>'
        '<cellXfs count="6">'
        # 0 = normal
        '<xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0">'
        '<alignment wrapText="1" vertical="top"/></xf>'
        # 1 = bold header (white on blue)
        '<xf numFmtId="0" fontId="2" fillId="2" borderId="1" xfId="0">'
        '<alignment wrapText="1" vertical="center" horizontal="center"/></xf>'
        # 2 = disclaimer (yellow fill, bold)
        '<xf numFmtId="0" fontId="1" fillId="3" borderId="1" xfId="0">'
        '<alignment wrapText="1" vertical="top"/></xf>'
        # 3 = normal with border + wrap
        '<xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0">'
        '<alignment wrapText="1" vertical="top"/></xf>'
        # 4 = bold with border (for module name)
        '<xf numFmtId="0" fontId="1" fillId="0" borderId="1" xfId="0">'
        '<alignment wrapText="1" vertical="top"/></xf>'
        # 5 = centered with border
        '<xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0">'
        '<alignment wrapText="1" vertical="top" horizontal="center"/></xf>'
        '</cellXfs>'
        '</styleSheet>'
    )
    files["xl/styles.xml"] = styles_xml.encode("utf-8")

    # -----------------------------------------------------------------------
    # Helper: build a sheet XML from rows
    # -----------------------------------------------------------------------
    COL_LETTERS = ["A", "B", "C", "D", "E", "F", "G", "H"]

    def build_sheet_xml(rows, col_widths=None, header_row=3):
        """header_row is 1-based row index of the header (for styling)."""
        xml_rows = []
        for row_idx, row in enumerate(rows, start=1):
            if not row:
                xml_rows.append(f'<row r="{row_idx}"/>')
                continue
            cells = []
            for col_idx, cell in enumerate(row):
                col_letter = COL_LETTERS[col_idx]
                ref = f"{col_letter}{row_idx}"
                val, typ = cell

                # Determine style
                if row_idx == 1:
                    # disclaimer
                    style = ' s="2"'
                elif row_idx == header_row:
                    style = ' s="1"'
                elif typ == "n":
                    style = ' s="5"'
                elif col_idx == 1 and row_idx > header_row:
                    # module name column - bold
                    style = ' s="4"'
                else:
                    style = ' s="3"'

                if typ == "s":
                    cells.append(
                        f'<c r="{ref}" t="s"{style}><v>{val}</v></c>'
                    )
                else:
                    cells.append(
                        f'<c r="{ref}"{style}><v>{val}</v></c>'
                    )
            xml_rows.append(
                f'<row r="{row_idx}">' + "".join(cells) + "</row>"
            )

        cols_xml = ""
        if col_widths:
            col_els = "".join(
                f'<col min="{i+1}" max="{i+1}" width="{w}" customWidth="1"/>'
                for i, w in enumerate(col_widths)
            )
            cols_xml = f"<cols>{col_els}</cols>"

        return (
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"'
            ' xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
            f'{cols_xml}'
            '<sheetData>'
            + "".join(xml_rows) +
            '</sheetData>'
            '</worksheet>'
        )

    files["xl/worksheets/sheet1.xml"] = build_sheet_xml(
        sheet1_rows,
        col_widths=[8, 22, 18, 60, 50, 40],
        header_row=3,
    ).encode("utf-8")

    files["xl/worksheets/sheet2.xml"] = build_sheet_xml(
        sheet2_rows,
        col_widths=[8, 22, 80],
        header_row=3,
    ).encode("utf-8")

    files["xl/worksheets/sheet3.xml"] = build_sheet_xml(
        sheet3_rows,
        col_widths=[10, 30, 28, 45, 70],
        header_row=3,
    ).encode("utf-8")

    # -----------------------------------------------------------------------
    # workbook.xml
    # -----------------------------------------------------------------------
    workbook_xml = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"'
        ' xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
        '<sheets>'
        '<sheet name="Module Overview" sheetId="1" r:id="rId1"/>'
        '<sheet name="Requirements to Go Live" sheetId="2" r:id="rId2"/>'
        '<sheet name="Tentative Timeline" sheetId="3" r:id="rId3"/>'
        '</sheets>'
        '</workbook>'
    )
    files["xl/workbook.xml"] = workbook_xml.encode("utf-8")

    # -----------------------------------------------------------------------
    # Relationships
    # -----------------------------------------------------------------------
    workbook_rels = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" '
        'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" '
        'Target="worksheets/sheet1.xml"/>'
        '<Relationship Id="rId2" '
        'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" '
        'Target="worksheets/sheet2.xml"/>'
        '<Relationship Id="rId3" '
        'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" '
        'Target="worksheets/sheet3.xml"/>'
        '<Relationship Id="rId4" '
        'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" '
        'Target="sharedStrings.xml"/>'
        '<Relationship Id="rId5" '
        'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" '
        'Target="styles.xml"/>'
        '</Relationships>'
    )
    files["xl/_rels/workbook.xml.rels"] = workbook_rels.encode("utf-8")

    root_rels = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" '
        'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" '
        'Target="xl/workbook.xml"/>'
        '</Relationships>'
    )
    files["_rels/.rels"] = root_rels.encode("utf-8")

    # -----------------------------------------------------------------------
    # [Content_Types].xml
    # -----------------------------------------------------------------------
    content_types = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        '<Default Extension="rels" '
        'ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        '<Default Extension="xml" ContentType="application/xml"/>'
        '<Override PartName="/xl/workbook.xml" '
        'ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'
        '<Override PartName="/xl/worksheets/sheet1.xml" '
        'ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
        '<Override PartName="/xl/worksheets/sheet2.xml" '
        'ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
        '<Override PartName="/xl/worksheets/sheet3.xml" '
        'ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
        '<Override PartName="/xl/sharedStrings.xml" '
        'ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml"/>'
        '<Override PartName="/xl/styles.xml" '
        'ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'
        '</Types>'
    )
    files["[Content_Types].xml"] = content_types.encode("utf-8")

    return files


def main():
    files = build_workbook()
    with zipfile.ZipFile(OUTPUT_PATH, "w", zipfile.ZIP_DEFLATED) as zf:
        for name, data in files.items():
            zf.writestr(name, data)
    size = os.path.getsize(OUTPUT_PATH)
    print(f"Created: {OUTPUT_PATH} ({size:,} bytes)")


if __name__ == "__main__":
    main()
