#!/usr/bin/env python3
"""
Creates OmniBlend_Module_Documentation.docx using only Python stdlib (zipfile).
A docx file is a zip archive containing XML files.
"""

import zipfile
import os

OUTPUT_PATH = "/home/user/LubeOilSim/OmniBlend_Module_Documentation.docx"

# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------
def xe(s):
    return (str(s)
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;"))

# ---------------------------------------------------------------------------
# Data (same as xlsx script)
# ---------------------------------------------------------------------------
DISCLAIMER = (
    "Note: All timelines are tentative estimates. Actual durations will depend on "
    "site readiness, data availability, system access, and integration complexity."
)

MODULES = [
    {
        "num": 1,
        "name": "Command Dashboard",
        "status": "Simulated / Built",
        "function": (
            "Central operations overview showing live KPIs (production volume, cost per batch, "
            "energy usage, equipment utilisation, on-spec rate), a live event feed of alerts, "
            "an operations timeline, an energy consumption heatmap, and equipment health meters."
        ),
        "current_state": (
            "Fully simulated — all values are generated by the simulation engine."
        ),
        "reqs": [
            "Production volumes from the manufacturing / ERP system",
            "Energy readings from building smart meters",
            "Equipment status signals from plant control systems (SCADA)",
            "Quality pass/fail results from the laboratory system (LIMS)",
            "Real alerts forwarded from SCADA, LIMS, and manufacturing systems",
        ],
        "phases": "Phase 3 (SCADA), Phase 4 (LIMS), Phase 5 (MES/ERP), Phase 8 (Energy)",
    },
    {
        "num": 2,
        "name": "Blend Simulator",
        "status": "Simulated / Built",
        "function": (
            "Manages blending batches through their full lifecycle — queued \u2192 mixing \u2192 "
            "sampling \u2192 lab \u2192 completed. Shows real-time batch temperature, mixing speed (RPM), "
            "progress percentage, and volume. Animated pipeline shows material flow between tanks."
        ),
        "current_state": (
            "Fully simulated — batch stages progress on a timer; temperature and RPM drift "
            "based on simulation engine ticks."
        ),
        "reqs": [
            "Batch stage signals from plant control systems (SCADA/PLC)",
            "Real-time blender temperature from thermocouple sensors",
            "Mixing speed feedback from Variable Frequency Drives",
            "Volume readings from flow meters or weighing systems",
            "Production orders imported from the manufacturing system (MES/ERP)",
        ],
        "phases": "Phase 3 (SCADA sensors), Phase 5 (MES/ERP orders)",
    },
    {
        "num": 3,
        "name": "Tank Digital Twin",
        "status": "Simulated / Built",
        "function": (
            "Visual tank farm layout showing all 12 tanks with animated fill levels, material "
            "types, temperatures, and status (Normal / Low / Critical). Supports drag-and-drop "
            "tank allocation and low-stock alerts with glowing indicators."
        ),
        "current_state": (
            "Fully simulated — fill levels drift with Gaussian noise; temperatures drift slowly "
            "per simulation tick."
        ),
        "reqs": [
            "Level sensors on each of the 12 tanks (ultrasonic or radar transmitters via SCADA)",
            "Temperature sensors per tank (thermocouple or RTD via SCADA)",
            "Tank material assignments from the manufacturing/ERP system",
            "Physical tank capacity data from plant datasheets (one-time configuration)",
        ],
        "phases": "Phase 3 (SCADA sensors), Phase 5 (material assignments from ERP)",
    },
    {
        "num": 4,
        "name": "Recipe Lab",
        "status": "Simulated / Built",
        "function": (
            "Create and modify lubricant formulations using ingredient sliders (base oil, "
            "viscosity modifier, antioxidant, detergent, PPD). AI engine predicts viscosity, "
            "flash point, and TBN in real time. Includes cost-per-litre display, three AI "
            "suggest modes (cost / quality / balanced), and a recipe library with 10 pre-loaded "
            "seed formulations."
        ),
        "current_state": (
            "Fully simulated — predictions use polynomial regression on synthetic data; costs "
            "are hardcoded; recipes are hardcoded seeds (SAE grades, hydraulic, gear oil, etc.) "
            "not the real plant product codes."
        ),
        "reqs": [
            "Real recipe formulations synced from the ERP system (SAP PP-PI master recipe) "
            "to replace hardcoded seeds",
            "Historical batch data (200+ batches) for training accurate ML prediction models",
            "Live supplier pricing feed for accurate cost-per-litre calculations",
        ],
        "phases": "Phase 5 (ERP recipe sync), Phase 6 (live pricing), Phase 7 (real ML models)",
    },
    {
        "num": 5,
        "name": "Quality AI Engine",
        "status": "Simulated / Built",
        "function": (
            "Live quality prediction graphs with confidence intervals, an off-spec risk meter "
            "(0\u2013100%), AI recommendations with impact levels, and a side-by-side predicted vs "
            "actual quality comparison table."
        ),
        "current_state": (
            "Fully simulated — predictions are formula-based; confidence intervals are hardcoded "
            "at \u00b15%; the predicted vs actual comparison table shows dummy data; risk meter uses "
            "hardcoded thresholds."
        ),
        "reqs": [
            "Laboratory system (LIMS) integration to receive actual test results (viscosity, "
            "flash point, TBN) within 5 minutes of analyst sign-off",
            "Historical lab results (200\u2013500 batches) to train accurate ML prediction models",
            "Real batch data to calculate genuine confidence intervals",
            "Automated off-spec alert triggering a batch hold when LIMS returns a fail",
        ],
        "phases": "Phase 4 (LIMS integration), Phase 7 (real ML models)",
    },
    {
        "num": 6,
        "name": "Supply & Cost Optimizer",
        "status": "Simulated / Built",
        "function": (
            "Multi-supplier selection interface showing price per litre, lead time, quality "
            "grade, and reliability score per supplier. AI optimizer suggests the cheapest and "
            "best-quality supplier mix. Dynamic cost breakdown pie chart and 6-month price trend "
            "charts."
        ),
        "current_state": (
            "Fully simulated — all supplier data (prices, lead times, quality grades, reliability "
            "scores) is hardcoded static data."
        ),
        "reqs": [
            "Live supplier pricing feeds via EDI or supplier REST APIs (updated daily)",
            "Lead times derived from ERP purchase order history",
            "Quality grades from incoming raw material QC results (LIMS)",
            "Reliability scores calculated from ERP on-time delivery history (rolling 12-month)",
        ],
        "phases": "Phase 5 (quality grades from LIMS), Phase 6 (live pricing and ERP data)",
    },
    {
        "num": 7,
        "name": "AI Control Panel",
        "status": "Simulated / Built",
        "function": (
            'Natural language command interface (e.g. "Start blend B101", "Optimise recipe for '
            'cost"). Includes quick command buttons, a what-if scenario comparison with radar '
            "charts (3 pre-configured scenarios), and injectable simulation events (equipment "
            "failure, material shortage, quality deviation)."
        ),
        "current_state": (
            "Functional simulator \u2014 commands are parsed using keyword/regex matching (no real "
            "NLP). Scenarios and event injection work within the simulator."
        ),
        "reqs": [
            "Claude API (Anthropic) integration to replace regex matching with real natural "
            "language understanding",
            "Connection routing from NL commands to all live module APIs",
            "Response caching and graceful fallback for API downtime",
        ],
        "phases": "Phase 8 (Claude API NLP integration)",
    },
]

PHASES = [
    {
        "phase": "Phase 1",
        "name": "Infrastructure Foundation",
        "weeks": "Weeks 1\u20134",
        "modules": "All (underpins everything)",
        "key_work": (
            "Cloud/server setup, database deployment, caching layer, SSL, "
            "environment separation, load testing."
        ),
    },
    {
        "phase": "Phase 2",
        "name": "Security & Access Control",
        "weeks": "Weeks 3\u20136 (overlaps Phase 1)",
        "modules": "All",
        "key_work": (
            "User authentication, role-based access (4 roles: Operator, Engineer, Manager, "
            "Read-Only), secure network tunnels between plant and platform, secrets management, "
            "audit logging."
        ),
    },
    {
        "phase": "Phase 3",
        "name": "SCADA / Plant Sensor Connection",
        "weeks": "Weeks 5\u201310",
        "modules": "Tank Digital Twin, Blend Simulator, Command Dashboard",
        "key_work": (
            "Connect 12 tank level + 12 tank temperature sensors; connect blender RPM and "
            "temperature; connect flow meters; forward SCADA alarms to event feed."
        ),
    },
    {
        "phase": "Phase 4",
        "name": "Laboratory System Integration",
        "weeks": "Weeks 8\u201314",
        "modules": "Quality AI Engine, Command Dashboard (On-Spec Rate KPI)",
        "key_work": (
            "Connect LIMS to receive real lab results within 5 minutes of sign-off; activate "
            "predicted vs actual panel; enable off-spec batch hold alerts; begin accumulating "
            "lab data for future ML training."
        ),
    },
    {
        "phase": "Phase 5",
        "name": "Manufacturing & ERP Sync",
        "weeks": "Weeks 12\u201318",
        "modules": "Blend Simulator, Recipe Lab, Tank Digital Twin, Command Dashboard",
        "key_work": (
            "Auto-import production orders; sync real recipe formulations from ERP (retire "
            "hardcoded seeds); bidirectional batch stage sync; material consumption data postback "
            "to ERP; real operations timeline."
        ),
    },
    {
        "phase": "Phase 6",
        "name": "Supplier Pricing Feed",
        "weeks": "Weeks 16\u201320",
        "modules": "Supply & Cost Optimizer, Recipe Lab",
        "key_work": (
            "Connect live supplier pricing; derive lead times from ERP purchase history; "
            "calculate reliability scores from on-time delivery data; Cost per Batch KPI "
            "becomes real."
        ),
    },
    {
        "phase": "Phase 7",
        "name": "ML Model Training",
        "weeks": "Weeks 18\u201324",
        "modules": "Recipe Lab, Quality AI Engine, Supply & Cost Optimizer",
        "key_work": (
            "Train viscosity, flash point, and TBN prediction models on 200+ real batches "
            "(target accuracy R\u00b2>0.92); train off-spec risk classifier; replace hardcoded "
            "confidence intervals with real model performance; upgrade AI recipe suggestions "
            "to use constrained optimisation."
        ),
    },
    {
        "phase": "Phase 8",
        "name": "Go-Live & Observability",
        "weeks": "Weeks 22\u201326",
        "modules": "AI Control Panel, Command Dashboard (Energy Heatmap)",
        "key_work": (
            "Activate Claude API for AI Control Panel NLP; connect energy heatmap to real "
            "building management data; set up application monitoring, log aggregation, and "
            "on-call alerting; operator training; phased go-live with 4-week support period."
        ),
    },
]

# ---------------------------------------------------------------------------
# Word namespace constants
# ---------------------------------------------------------------------------
W_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
R_NS = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"

# ---------------------------------------------------------------------------
# XML building helpers
# ---------------------------------------------------------------------------

def para(text, style="Normal", bold=False, size=None, color=None, indent=None):
    """Build a <w:p> paragraph element as a string."""
    rpr_parts = []
    if bold:
        rpr_parts.append("<w:b/>")
    if size:
        rpr_parts.append(f'<w:sz w:val="{size}"/><w:szCs w:val="{size}"/>')
    if color:
        rpr_parts.append(f'<w:color w:val="{color}"/>')
    rpr = f"<w:rPr>{''.join(rpr_parts)}</w:rPr>" if rpr_parts else ""

    ppr_parts = [f'<w:pStyle w:val="{style}"/>']
    if indent:
        ppr_parts.append(f'<w:ind w:left="{indent}"/>')
    ppr = f"<w:pPr>{''.join(ppr_parts)}</w:pPr>"

    # Handle multi-line text: split on newlines
    lines = str(text).split("\n")
    runs = []
    for i, line in enumerate(lines):
        if i > 0:
            runs.append("<w:r><w:br/></w:r>")
        runs.append(f"<w:r>{rpr}<w:t xml:space=\"preserve\">{xe(line)}</w:t></w:r>")

    return f"<w:p>{ppr}{''.join(runs)}</w:p>"


def heading1(text):
    return para(text, style="Heading1")


def heading2(text):
    return para(text, style="Heading2")


def heading3(text):
    return para(text, style="Heading3")


def label_value(label, value):
    """Bold label followed by normal value in same paragraph."""
    rpr_bold = "<w:rPr><w:b/></w:rPr>"
    rpr_norm = "<w:rPr></w:rPr>"
    ppr = '<w:pPr><w:pStyle w:val="Normal"/></w:pPr>'
    label_run = f'<w:r>{rpr_bold}<w:t xml:space="preserve">{xe(label)}</w:t></w:r>'
    value_run = f'<w:r>{rpr_norm}<w:t xml:space="preserve">{xe(value)}</w:t></w:r>'
    return f"<w:p>{ppr}{label_run}{value_run}</w:p>"


def bullet(text):
    """A bulleted list item using ListParagraph style."""
    ppr = (
        '<w:pPr>'
        '<w:pStyle w:val="ListParagraph"/>'
        '<w:numPr><w:ilvl w:val="0"/><w:numId w:val="1"/></w:numPr>'
        '</w:pPr>'
    )
    return f'<w:p>{ppr}<w:r><w:t xml:space="preserve">{xe(text)}</w:t></w:r></w:p>'


def blank():
    return '<w:p><w:pPr><w:pStyle w:val="Normal"/></w:pPr></w:p>'


def disclaimer_para(text):
    """Highlighted disclaimer paragraph."""
    ppr = '<w:pPr><w:pStyle w:val="Normal"/><w:shd w:val="clear" w:color="auto" w:fill="FFF2CC"/></w:pPr>'
    rpr = "<w:rPr><w:b/><w:color w:val=\"7F6000\"/></w:rPr>"
    return (
        f'<w:p>{ppr}'
        f'<w:r>{rpr}<w:t xml:space="preserve">{xe(text)}</w:t></w:r>'
        f'</w:p>'
    )


def horizontal_rule():
    """Paragraph with a bottom border acting as a divider."""
    return (
        '<w:p>'
        '<w:pPr>'
        '<w:pBdr>'
        '<w:bottom w:val="single" w:sz="6" w:space="1" w:color="4472C4"/>'
        '</w:pBdr>'
        '</w:pPr>'
        '</w:p>'
    )


# ---------------------------------------------------------------------------
# Build document body
# ---------------------------------------------------------------------------
def build_body():
    parts = []

    # Cover heading
    parts.append(
        '<w:p>'
        '<w:pPr><w:pStyle w:val="Title"/></w:pPr>'
        '<w:r><w:t>OmniBlend Simulator</w:t></w:r>'
        '</w:p>'
    )
    parts.append(
        '<w:p>'
        '<w:pPr><w:pStyle w:val="Subtitle"/></w:pPr>'
        '<w:r><w:t>Module Documentation</w:t></w:r>'
        '</w:p>'
    )
    parts.append(blank())
    parts.append(disclaimer_para(DISCLAIMER))
    parts.append(blank())
    parts.append(horizontal_rule())
    parts.append(blank())

    # Modules
    for m in MODULES:
        parts.append(heading1(f"Module {m['num']}: {m['name']}"))
        parts.append(label_value("Status: ", m["status"]))
        parts.append(blank())

        parts.append(heading2("Function"))
        parts.append(para(m["function"]))
        parts.append(blank())

        parts.append(heading2("Current State"))
        parts.append(para(m["current_state"]))
        parts.append(blank())

        parts.append(heading2("Requirements to Go Live"))
        for req in m["reqs"]:
            parts.append(bullet(req))
        parts.append(blank())

        parts.append(heading2("Timeline Phases"))
        parts.append(para(m["phases"]))
        parts.append(blank())
        parts.append(horizontal_rule())
        parts.append(blank())

    # Timeline section
    parts.append(heading1("Tentative Implementation Timeline"))
    parts.append(disclaimer_para(DISCLAIMER))
    parts.append(blank())

    for p in PHASES:
        parts.append(heading2(f"{p['phase']}: {p['name']}"))
        parts.append(label_value("Estimated Weeks: ", p["weeks"]))
        parts.append(label_value("Modules Affected: ", p["modules"]))
        parts.append(blank())
        parts.append(heading3("Key Work"))
        parts.append(para(p["key_work"]))
        parts.append(blank())

    return "".join(parts)


# ---------------------------------------------------------------------------
# Build the docx archive
# ---------------------------------------------------------------------------
def build_docx():
    files = {}

    body_content = build_body()

    # -----------------------------------------------------------------------
    # numbering.xml — define bullet list (numId=1)
    # -----------------------------------------------------------------------
    numbering_xml = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<w:numbering xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
        '<w:abstractNum w:abstractNumId="0">'
        '<w:lvl w:ilvl="0">'
        '<w:start w:val="1"/>'
        '<w:numFmt w:val="bullet"/>'
        '<w:lvlText w:val="\u2022"/>'
        '<w:lvlJc w:val="left"/>'
        '<w:pPr><w:ind w:left="720" w:hanging="360"/></w:pPr>'
        '<w:rPr><w:rFonts w:ascii="Symbol" w:hAnsi="Symbol" w:hint="default"/></w:rPr>'
        '</w:lvl>'
        '</w:abstractNum>'
        '<w:num w:numId="1">'
        '<w:abstractNumId w:val="0"/>'
        '</w:num>'
        '</w:numbering>'
    )
    files["word/numbering.xml"] = numbering_xml.encode("utf-8")

    # -----------------------------------------------------------------------
    # document.xml
    # -----------------------------------------------------------------------
    document_xml = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<w:document '
        'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
        'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
        '<w:body>'
        + body_content +
        '<w:sectPr>'
        '<w:pgSz w:w="12240" w:h="15840"/>'
        '<w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" '
        'w:header="720" w:footer="720" w:gutter="0"/>'
        '</w:sectPr>'
        '</w:body>'
        '</w:document>'
    )
    files["word/document.xml"] = document_xml.encode("utf-8")

    # -----------------------------------------------------------------------
    # styles.xml — define Heading1, Heading2, Heading3, Normal, Title, Subtitle, ListParagraph
    # -----------------------------------------------------------------------
    styles_xml = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'

        # Default / Normal
        '<w:style w:type="paragraph" w:default="1" w:styleId="Normal">'
        '<w:name w:val="Normal"/>'
        '<w:pPr><w:spacing w:after="120"/></w:pPr>'
        '<w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:sz w:val="20"/><w:szCs w:val="20"/></w:rPr>'
        '</w:style>'

        # Title
        '<w:style w:type="paragraph" w:styleId="Title">'
        '<w:name w:val="Title"/>'
        '<w:basedOn w:val="Normal"/>'
        '<w:pPr><w:jc w:val="center"/><w:spacing w:after="240"/></w:pPr>'
        '<w:rPr><w:b/><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/>'
        '<w:sz w:val="52"/><w:szCs w:val="52"/>'
        '<w:color w:val="1F3864"/></w:rPr>'
        '</w:style>'

        # Subtitle
        '<w:style w:type="paragraph" w:styleId="Subtitle">'
        '<w:name w:val="Subtitle"/>'
        '<w:basedOn w:val="Normal"/>'
        '<w:pPr><w:jc w:val="center"/><w:spacing w:after="480"/></w:pPr>'
        '<w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/>'
        '<w:sz w:val="32"/><w:szCs w:val="32"/>'
        '<w:color w:val="2F5496"/></w:rPr>'
        '</w:style>'

        # Heading1
        '<w:style w:type="paragraph" w:styleId="Heading1">'
        '<w:name w:val="heading 1"/>'
        '<w:basedOn w:val="Normal"/>'
        '<w:pPr>'
        '<w:spacing w:before="360" w:after="120"/>'
        '<w:shd w:val="clear" w:color="auto" w:fill="2F5496"/>'
        '</w:pPr>'
        '<w:rPr><w:b/><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/>'
        '<w:sz w:val="28"/><w:szCs w:val="28"/>'
        '<w:color w:val="FFFFFF"/></w:rPr>'
        '</w:style>'

        # Heading2
        '<w:style w:type="paragraph" w:styleId="Heading2">'
        '<w:name w:val="heading 2"/>'
        '<w:basedOn w:val="Normal"/>'
        '<w:pPr>'
        '<w:spacing w:before="240" w:after="60"/>'
        '<w:pBdr>'
        '<w:bottom w:val="single" w:sz="4" w:space="1" w:color="4472C4"/>'
        '</w:pBdr>'
        '</w:pPr>'
        '<w:rPr><w:b/><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/>'
        '<w:sz w:val="24"/><w:szCs w:val="24"/>'
        '<w:color w:val="2F5496"/></w:rPr>'
        '</w:style>'

        # Heading3
        '<w:style w:type="paragraph" w:styleId="Heading3">'
        '<w:name w:val="heading 3"/>'
        '<w:basedOn w:val="Normal"/>'
        '<w:pPr><w:spacing w:before="180" w:after="60"/></w:pPr>'
        '<w:rPr><w:b/><w:i/><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/>'
        '<w:sz w:val="22"/><w:szCs w:val="22"/>'
        '<w:color w:val="1F3864"/></w:rPr>'
        '</w:style>'

        # ListParagraph
        '<w:style w:type="paragraph" w:styleId="ListParagraph">'
        '<w:name w:val="List Paragraph"/>'
        '<w:basedOn w:val="Normal"/>'
        '<w:pPr><w:ind w:left="720"/></w:pPr>'
        '</w:style>'

        '</w:styles>'
    )
    files["word/styles.xml"] = styles_xml.encode("utf-8")

    # -----------------------------------------------------------------------
    # settings.xml
    # -----------------------------------------------------------------------
    settings_xml = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<w:settings xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
        '<w:defaultTabStop w:val="720"/>'
        '</w:settings>'
    )
    files["word/settings.xml"] = settings_xml.encode("utf-8")

    # -----------------------------------------------------------------------
    # word/_rels/document.xml.rels
    # -----------------------------------------------------------------------
    doc_rels = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" '
        'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" '
        'Target="styles.xml"/>'
        '<Relationship Id="rId2" '
        'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings" '
        'Target="settings.xml"/>'
        '<Relationship Id="rId3" '
        'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering" '
        'Target="numbering.xml"/>'
        '</Relationships>'
    )
    files["word/_rels/document.xml.rels"] = doc_rels.encode("utf-8")

    # -----------------------------------------------------------------------
    # _rels/.rels
    # -----------------------------------------------------------------------
    root_rels = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" '
        'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" '
        'Target="word/document.xml"/>'
        '</Relationships>'
    )
    files["_rels/.rels"] = root_rels.encode("utf-8")

    # -----------------------------------------------------------------------
    # [Content_Types].xml
    # -----------------------------------------------------------------------
    content_types = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        '<Default Extension="rels" '
        'ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        '<Default Extension="xml" ContentType="application/xml"/>'
        '<Override PartName="/word/document.xml" '
        'ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
        '<Override PartName="/word/styles.xml" '
        'ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>'
        '<Override PartName="/word/settings.xml" '
        'ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml"/>'
        '<Override PartName="/word/numbering.xml" '
        'ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml"/>'
        '</Types>'
    )
    files["[Content_Types].xml"] = content_types.encode("utf-8")

    return files


def main():
    files = build_docx()
    with zipfile.ZipFile(OUTPUT_PATH, "w", zipfile.ZIP_DEFLATED) as zf:
        for name, data in files.items():
            zf.writestr(name, data)
    size = os.path.getsize(OUTPUT_PATH)
    print(f"Created: {OUTPUT_PATH} ({size:,} bytes)")


if __name__ == "__main__":
    main()
